### PR TITLE
Bootstrap runs as root, so sudo's are not needed

### PR DESCRIPTION
**Pull request by RichieB2B**
Sudo's are only for gpg that creates several files in .gpg as www-data

### CODE REVIEW

**Comment by 0xtf** [comment]
Have you checked the ones that run as www-data for git clone, for example? Makes sense to download code as the owner of the folder as I don't change permissions for that later.

**Comment by RichieB2B** [comment]
All permissions are reset on [line 502](https://github.com/RichieB2B/misp-cloud/blob/sudo/dev/bootstrap#L502). In general it could make sense to run `git` as a normal user because of `~/.git/config` but as this is a fresh Ubuntu image there is not difference between running `git` as `root` and `www-data` really.

**Comment by 0xtf** [comment]
Makes sense. I'll test this out in the build process and merge it after that.

**Comment by 0xtf** [comment]
Tested. Thank you!

**Pull request merged**
