### PR TITLE
Document AMI building

### PR DESCRIPTION
**Pull request by RichieB2B**
Not rocket science, but nice to have a basic guide

### CODE REVIEW

**Comment by iglocska** [comment]
Thanks a lot

**Comment by 0xtf** [comment]
@iglocska I don’t believe we should maintain this documentation due to it not being the objective of the project and also due to the fact that this is not how the images are built (doesn’t reflect the actual build process). 

There are far better projects that instruct on how to create images.

**Comment by RichieB2B** [comment]
It does reflect how I build my own images using the `packer-aws.json` from this project. I took me some time to figure it out, that's why I made the PR. There are several reasons why someone would want to build their own AMIs (I needed more customisation in the bootstrap).

If there is better documentation and/or your actual build process differs greatly, please update the README.md.

**Comment by 0xtf** [comment]
Having a document that explains how you build your image in the documentation of this project is not something I consider useful. To some extent, the opposite.

The reason I didn't add a README.md is because I didn't want to maintain one, so I don't understand why you're asking me to update the file you created. 

My point remains: maintaining documentation on how to build AMI's has nothing to do with the purpose of this particular project.

**Comment by 0xtf** [comment]
To add to me previous comment, and after reviewing the document:

- There is no need to install AWS Python SDK
- The document mentions how to build "misp-cloud images" but makes no reference to the bootstrap script nor the packer configuration file

Again, I fail to see how useful this might be for someone who wants to follow with the development files (which I made available for guidance, not as a tutorial).

**Comment by 0xtf** [comment]
I removed the file, for the time being. My last comment also didn't accurately describe why I don't believe this shouldn't be explained in the project page. 

MISP doesn't maintain a tutorial/guide on the usage of Vagrant either, and the demo VMs are mode widely used than these images. 

I'll update the readme with a generic pointer to packer.io, and this way we don't have to maintain it. I'll also mention the usage of the plugin for AMI.

**Comment by RichieB2B** [comment]
Makes sense. General pointers is all I wanted to contribute, not a comprehensive guide.

**Pull request merged**
